# Generated by Django 2.0.2 on 2018-03-01 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default=None, max_length=250)),
                ('contact_email', models.EmailField(default=None, max_length=150)),
                ('contact_telephone', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DevRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devrep_full_name', models.CharField(max_length=250, null=True)),
                ('devrep_email', models.EmailField(max_length=50)),
                ('devrep_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(default=None, max_length=250)),
                ('manufacturer_code', models.CharField(default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='manufarturer_billing_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufarturer_billing_name', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_contact_name', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_address', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_city', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_POBox', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_country', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_tax', models.CharField(default=None, max_length=250)),
                ('manufarturer_billing_phone', models.CharField(default=None, max_length=250)),
                ('manufacturer_name', models.ForeignKey(default=None, on_delete=None, to='form.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_description', models.TextField(default=None, max_length=3000)),
                ('Opportunity_name', models.TextField(default=None, max_length=1500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('file1', models.FileField(blank=True, null=True, upload_to='form.OpportunityFile/bytes/filename/mimetype')),
                ('file2', models.FileField(blank=True, null=True, upload_to='form.Opportunityfile/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0)),
                ('opportunity', models.ForeignKey(on_delete=None, to='form.Opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Request_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_status', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Technical_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_full_name', models.CharField(blank=True, default=None, max_length=250)),
                ('manager_email', models.EmailField(max_length=50)),
                ('manager_name', models.CharField(max_length=100)),
                ('still_working', models.BooleanField(default=False)),
                ('featured', models.IntegerField(choices=[(0, 'No'), (1, 'Everywhere'), (2, 'category-only')], default=0)),
                ('categories', models.ManyToManyField(to='form.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='task',
            field=models.ForeignKey(on_delete=None, to='form.Task'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='Technical_Manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.Technical_Manager'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.Contact_details'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='devrep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.DevRep'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='items',
            field=models.ManyToManyField(through='form.OpportunityTask', to='form.Task'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='jurisdiction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='request_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='form.Request_status'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='type_of_work',
            field=models.ForeignKey(default=None, on_delete=None, to='form.Type_of_work'),
        ),
        migrations.AddField(
            model_name='contact_details',
            name='manufacturer_name',
            field=models.ForeignKey(default=None, on_delete=None, to='form.Manufacturer'),
        ),
    ]
