# Generated by Django 2.0.2 on 2018-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical_manager',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='technical_manager',
            name='featured',
        ),
    ]
