# Generated by Django 2.0.2 on 2018-03-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180301_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='Opportunity_name',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
