# Generated by Django 2.0.2 on 2018-03-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20180301_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='Opportunity_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
