# Generated by Django 2.0.3 on 2018-03-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=150)),
                ('worker', models.CharField(default=None, max_length=150)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('first_entry', models.CharField(max_length=5)),
                ('last_entry', models.CharField(max_length=5)),
                ('gross_minutes_at_work', models.IntegerField(null=True)),
                ('gross_time_at_work', models.CharField(max_length=5)),
                ('net_time_at_work', models.CharField(default='', max_length=5)),
                ('time_reported', models.CharField(default='', max_length=5)),
                ('BP_hours', models.FloatField()),
                ('work_day', models.DateField()),
                ('day_name', models.CharField(blank=True, max_length=20)),
                ('month_work', models.IntegerField()),
                ('adp_comments', models.CharField(default='', max_length=100)),
                ('source_of_records', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'fob_entry',
            },
        ),
    ]
