# Generated by Django 2.0.3 on 2018-04-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(choices=[('Business trip', 'Business trip'), ('Sick leave', 'Sick leave'), ('Work from home', 'Work from home')], default='', max_length=50)),
                ('hours', models.FloatField()),
            ],
            options={
                'db_table': 'worker_report',
            },
        ),
    ]
