# Generated by Django 2.0.3 on 2018-04-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fob', '0002_worker_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_report',
            name='day',
            field=models.DateField(),
        ),
    ]
