# Generated by Django 2.0.3 on 2018-04-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fob', '0003_auto_20180409_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_report',
            name='user_name',
            field=models.CharField(default='gil_g', max_length=50),
        ),
    ]
