# Generated by Django 2.0.3 on 2018-04-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fob', '0005_auto_20180409_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='net_minutes_at_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='worker_report',
            name='user_comment',
            field=models.CharField(choices=[('Business trip', 'Business trip'), ('Work from home', 'Work from home')], default='', max_length=50),
        ),
    ]
